# Site settings
title: Great New Blog Title
author:
  name: Hoang Minh Phan
  email: test_@gmail.com
  
description: "Great site about Jekyll on Github page."

# Build setting
remote_theme: jekyll/minima@1e8a445
